table Customers
	excludeFromModelRefresh
	lineageTag: defdcd3d-ba66-43c5-88f0-964f1738889d

	measure 'Total Customers' = DISTINCTCOUNT(Customers[customer_id])
		formatString: 0
		lineageTag: 60c96129-5ce9-4a63-8d73-a1da17fa1b36

	measure 'Avg Age' = AVERAGE(Customers[Current Age])
		lineageTag: b1c562a8-55b7-4342-b086-e976fde849ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'High Priority %' = DIVIDE(CALCULATE([Total Customers], Customers[Priority]="High"), [Total Customers])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0d0f79ed-afe9-40f7-9ff8-2f3607c7857e

	measure 'Homeowners %' = DIVIDE(CALCULATE([Total Customers], Customers[homeowner]="Y"), [Total Customers])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9610d908-adc7-4b51-83f9-2deb286276e2

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 90d33fad-4855-4540-8c90-8f826d15e978
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: string
		lineageTag: 458d5a16-082f-4117-a566-1a6defa7293d
		summarizeBy: none
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: ee98d268-9331-4711-9b86-21617b6c1582
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: ec9489ba-668f-4b45-8e8f-de56f9277fb5
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column customer_address
		dataType: string
		lineageTag: 9d6ffd99-7fd1-45a6-9ac8-960af71af2ee
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 58e43ef3-f61c-43e0-b2f8-645fb84eea75
		dataCategory: City
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state_province
		dataType: string
		lineageTag: 7ac0846b-d158-4b32-a5d7-c10bb3388442
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

	column customer_postal_code
		dataType: string
		lineageTag: 35850053-1777-4ed7-a87b-443e9844d806
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: bea574ab-de63-4906-8635-a5c3ec81d5f1
		dataCategory: Country
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column birthdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: c1fbd632-7941-4d6d-b4c1-9f348ad60817
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: d1c68c6f-c6d7-4a76-9803-4fe236ab8a48
			defaultHierarchy: LocalDateTable_7586d8d0-ccef-4059-b627-f65d886eef0a.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: 7a31344c-73ad-4415-a774-b95210d6f571
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column yearly_income
		dataType: string
		lineageTag: a46dae24-dcf3-4ec1-8408-804caa45f29d
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 89b59775-01db-42c2-b3fb-c371fb9e06de
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column total_children
		dataType: string
		lineageTag: 353c139d-05f7-41b6-b68f-b2c056f4185c
		summarizeBy: none
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: string
		lineageTag: 5bf10624-1629-4289-9152-8dae93d3a865
		summarizeBy: none
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: de310370-f269-4fe8-8531-05065430b7e6
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column acct_open_date
		dataType: string
		lineageTag: 417c0f31-fa6d-43ae-bb97-abfaf7ad0fa5
		summarizeBy: none
		sourceColumn: acct_open_date

		annotation SummarizationSetBy = Automatic

	column member_card
		dataType: string
		lineageTag: 1e0ddb59-4d06-4cff-935f-573f6f06cc9f
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

	column occupation
		dataType: string
		lineageTag: 05b4c095-9b4f-4c8d-9d18-556c636b7605
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

	column homeowner
		dataType: string
		lineageTag: 1a82d54d-bb77-4d1e-bab5-43808c705500
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: 5328c92f-29c5-442f-956d-833a86e59021
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	column 'Birth Year'
		dataType: string
		lineageTag: fa2da134-1c70-485a-b307-b53475a99ca1
		summarizeBy: none
		sourceColumn: Birth Year

		annotation SummarizationSetBy = Automatic

	column has_children
		dataType: string
		lineageTag: d3d3d848-e4a9-4932-9b6a-1702fc04c40e
		summarizeBy: none
		sourceColumn: has_children

		annotation SummarizationSetBy = Automatic

	column 'Current Age' = DATEDIFF(Customers[birthdate], TODAY(), YEAR)
		formatString: 0
		lineageTag: bfe045bf-1ada-4554-841a-b0e418bdd532
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Customers","TableItemName":"Age Band","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Priority = IF(Customers[homeowner] = "Y" && Customers[member_card] = "Golden", "High", "Standard")
		lineageTag: f28c21ba-6433-4d71-a461-e0bf458848d1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Short_Country = UPPER(LEFT(Customers[customer_country], 3))
		lineageTag: a22b23a0-9c5f-49da-91ac-f24e3cfe6fca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'House Number' = LEFT(Customers[customer_address], SEARCH(" ", Customers[customer_address]) - 1)
		lineageTag: 44586719-1ffe-44bd-8f9f-48d77c88c23f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Age Band' =
			IF(
				ISBLANK('Customers'[Current Age]),
				BLANK(),
				INT('Customers'[Current Age] / 10) * 10
			)
		formatString: 0
		lineageTag: 722a52e3-a6f5-4195-8a25-415b2240202a
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Customers"
				          }
				        },
				        "Property": "Current Age"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 10.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"c","Entity":"Customers"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"Current Age"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"Current Age"}},"Size":10.0}}}}

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Owner\Downloads\Udemy\Power BI\Maven Market\MavenMarket_Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "Full Name", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Merged Column", "birthdate", "birthdate - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"birthdate - Copy", "Birth Year"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Birth Year", type date}}),
				    #"Extracted Year" = Table.TransformColumns(#"Changed Type1",{{"Birth Year", Date.Year, Int64.Type}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Extracted Year",{{"Birth Year", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type2", "has_children", each if [total_children] = "0" then "N" else "Y")
				in
				    #"Added Conditional Column"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

