table Stores
	excludeFromModelRefresh
	lineageTag: c2e8b3c8-cd33-45d8-865a-73a7e98d6410

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: 8d80377d-a0fb-4153-8649-12d452550b69
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 658f8641-fc8a-42dd-a9ca-08b4aa95f4d0
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_type
		dataType: string
		lineageTag: a50d18cf-676e-49f2-b29b-f273e134e8e2
		summarizeBy: none
		sourceColumn: store_type

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: e1abd3b5-5f61-495c-9c38-3499c5398b84
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column store_street_address
		dataType: string
		lineageTag: b4d8b082-346d-4baf-bc6e-d2fe529486b8
		summarizeBy: none
		sourceColumn: store_street_address

		annotation SummarizationSetBy = Automatic

	column store_city
		dataType: string
		lineageTag: f0ae050c-0558-43ca-91ee-1617c25af19f
		dataCategory: City
		summarizeBy: none
		sourceColumn: store_city

		annotation SummarizationSetBy = Automatic

	column store_state
		dataType: string
		lineageTag: 435d290b-86eb-4ee4-b79b-c0e24536ab6a
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: store_state

		annotation SummarizationSetBy = Automatic

	column store_country
		dataType: string
		lineageTag: c29519ad-78fd-49ad-b3cf-8462321dc2e6
		dataCategory: Country
		summarizeBy: none
		sourceColumn: store_country

		annotation SummarizationSetBy = Automatic

	column store_phone
		dataType: string
		lineageTag: 6a3a25d7-32ec-497c-80a2-c9851cedc7e4
		summarizeBy: none
		sourceColumn: store_phone

		annotation SummarizationSetBy = Automatic

	column first_opened_date
		dataType: string
		lineageTag: 8a296cff-cfad-425e-8ec4-313809692030
		summarizeBy: none
		sourceColumn: first_opened_date

		annotation SummarizationSetBy = Automatic

	column last_remodel_date
		dataType: string
		lineageTag: 84029907-7387-48c4-bad6-d5cec1163c1f
		summarizeBy: none
		sourceColumn: last_remodel_date

		annotation SummarizationSetBy = Automatic

	column total_sqft
		dataType: string
		lineageTag: 49f29c2d-b665-4ad8-adda-a1d3a49a2804
		summarizeBy: none
		sourceColumn: total_sqft

		annotation SummarizationSetBy = Automatic

	column grocery_sqft
		dataType: string
		lineageTag: 004f8821-99db-41f5-815f-f3e8f92e806c
		summarizeBy: none
		sourceColumn: grocery_sqft

		annotation SummarizationSetBy = Automatic

	column full_address
		dataType: string
		lineageTag: caacf488-0a01-40d1-97ab-c134ed31d767
		dataCategory: Address
		summarizeBy: none
		sourceColumn: full_address

		annotation SummarizationSetBy = Automatic

	column area_code
		dataType: string
		lineageTag: cc3e23db-8871-4bbf-9379-d838930f65c1
		summarizeBy: none
		sourceColumn: area_code

		annotation SummarizationSetBy = Automatic

	column Years_Since_Remodel = DATEDIFF(Stores[last_remodel_date], TODAY(), YEAR)
		formatString: 0
		lineageTag: bc5cb0b1-2c6a-49f2-ba0c-5d1323693be5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Owner\Downloads\Udemy\Power BI\Maven Market\MavenMarket_Stores.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"region_id", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "full_address", each Text.Combine({[store_state], [store_city], [store_country]}, ", "), type text),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Merged Column", "store_phone", "store_phone - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"store_phone - Copy", "area_code"}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([area_code], "-"), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Text Before Delimiter",{"area_code"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Text Before Delimiter", "area_code"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Camacho","Estación Camacho",Replacer.ReplaceText,{"store_city"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","San Andres","Mexico City",Replacer.ReplaceText,{"store_city"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

