table 'Transaction Data'
	lineageTag: 5057b0b6-dc0c-4cb4-bdc0-d32f55de089a

	measure 'Quantity Sold' = SUM('Transaction Data'[quantity])
		formatString: 0
		lineageTag: 1a541256-9422-4487-9595-7cf85cb99637

	measure 'Total Transactions' = COUNTROWS('Transaction Data')
		formatString: 0
		lineageTag: 591e2d77-4903-40ef-9149-273b2e11f5ae

	measure 'All Transactions' = CALCULATE([Total Transactions], ALL('Transaction Data'))
		formatString: 0
		lineageTag: 54d0f25b-8eac-430e-8a34-78fa14289a08

	measure 'Total Revenue' = SUMX('Transaction Data', 'Transaction Data'[quantity] * RELATED(Products[product_retail_price]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eda8286e-2d1a-49c1-a646-d93d6a507e7b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Cost' = SUMX('Transaction Data', 'Transaction Data'[quantity] * RELATED(Products[product_cost]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2cbea374-7162-4483-98d5-6fdf7e542295

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Profit' = [Total Revenue] - [Total Cost]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f1bd6ed8-50b3-4fbd-b690-3d6a85c6a6ac

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Profit Margin' = DIVIDE([Total Profit], [Total Revenue])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 303b3120-5cdf-4bee-afba-188e0efd6340

	measure 'Weekend Transactions' = CALCULATE([Total Transactions], 'Calendar'[WEEKEND] = "Y")
		formatString: 0
		lineageTag: 0db42fa7-b318-4889-8891-05de364d6610

	measure '% Weekend Transactions' = DIVIDE([Weekend Transactions], [Total Transactions])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 83883975-8820-4f5e-aa4e-156950c4dda0

	measure 'YTD Revenue' = TOTALYTD([Total Revenue], 'Calendar'[date])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 740259b0-2cb4-4706-a443-0518a5ad1463

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '60-Day Revenue' = CALCULATE([Total Revenue], DATESINPERIOD('Calendar'[date], MAX('Calendar'[date]), -60, DAY))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6d7871ca-5d96-49a8-849b-3c75247aaac9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Last Month Transactions' = CALCULATE([Total Revenue], DATEADD('Calendar'[date], -1, MONTH))
		lineageTag: 0ffc0f99-6954-435b-bc2d-f272fa991ff7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Month Revenue' = CALCULATE([Total Revenue], DATEADD('Calendar'[date], -1, MONTH))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b1a31287-342b-4d8e-9f38-b8b1fdaa80bc

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Last Month Profit' = CALCULATE([Total Profit], DATEADD('Calendar'[date], -1, MONTH))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e1d19c00-82b5-43ef-95fa-eeace3f00569

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Target' = [Last Month Revenue] * 1.05
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8908fdce-078e-4b32-8f51-a7080ccb180f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column transaction_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4dfdfd3d-ba27-436c-83be-283a76539fde
		summarizeBy: none
		sourceColumn: transaction_date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column stock_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: b5d9b435-bb32-4631-9a21-1632f01d4745
		summarizeBy: none
		sourceColumn: stock_date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2eba27da-3d0e-4f04-bfcc-41dc32034e08
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b9a5e060-938a-4662-8f3f-0ce44f5d18ed
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 989ecc62-ece9-4028-899c-d1d5796b3138
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 74e3ec05-cba1-4993-bb6a-54de0a785ac0
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	partition 'Transaction Data' = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Owner\Downloads\Udemy\Power BI\Maven Market\MavenMarket_Transactions"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Table Column1",{"Source.Name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"product_id", Int64.Type}, {"customer_id", Int64.Type}, {"store_id", Int64.Type}, {"quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

